function f_sym = cartPoleDynamics(in1,force_sym,in3)
%CARTPOLEDYNAMICS
%    F_SYM = CARTPOLEDYNAMICS(IN1,FORCE_SYM,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-May-2019 19:32:28

g_sym = in3(:,4);
lPole_sym = in3(:,3);
mCart_sym = in3(:,1);
mPole_sym = in3(:,2);
pdot_sym = in1(3,:);
theta_sym = in1(2,:);
thetadot_sym = in1(4,:);
t2 = conj(theta_sym);
t3 = cos(t2);
t4 = sin(t2);
t5 = conj(pdot_sym);
t6 = sin(theta_sym);
t7 = cos(theta_sym);
t8 = conj(mPole_sym);
t9 = mPole_sym-t8;
t10 = conj(lPole_sym);
t11 = conj(thetadot_sym);
t12 = 1.0./lPole_sym;
t13 = t3.*t7.*t9;
t14 = mPole_sym.*t4.*t6;
t15 = mCart_sym+t13+t14;
t16 = 1.0./t15;
t17 = (mPole_sym.*t4.*t5.*t10.*thetadot_sym)./2.0;
t18 = mPole_sym.*pdot_sym.*t4.*t5.*t7;
t33 = mPole_sym.*pdot_sym.*t3.*t5.*t6;
t19 = t17+t18-t33;
t20 = t12.*t19.*2.0;
t21 = pdot_sym.*t6.*t9.*thetadot_sym;
t22 = t20+t21-mPole_sym.*pdot_sym.*t6.*t11;
t23 = t3.*t22;
t24 = (mPole_sym.*t10.*t11.*thetadot_sym)./2.0;
t25 = mPole_sym.*pdot_sym.*t7.*t11;
t26 = t24+t25-mPole_sym.*pdot_sym.*t7.*thetadot_sym;
t27 = t4.*t26;
t28 = t4.*t7.*t8;
t29 = t3.*t6.*t9;
t30 = t28+t29;
t31 = g_sym.*t30;
t32 = force_sym+t23+t27+t31;
f_sym = [pdot_sym;thetadot_sym;t16.*t32;(t12.*(t17+t18-t33+(lPole_sym.*t8.*(g_sym.*t6-pdot_sym.*t6.*thetadot_sym+t7.*t16.*t32))./2.0).*-4.0)./(mPole_sym.*t10)];
